language: node_js
node_js:
 - 'stable'
install:
 - npm install
cache:
 directories:
 - node_modules
script: 
 - tslint -c tslint.json 'src/**/*.ts'
 - npm run test
after_success:
 - codecov -f coverage/*.json